# Generated by Django 4.1.2 on 2024-07-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brownie',
            fields=[
                ('id', models.AutoField(db_column='idBrownie', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
