# Generated by Django 4.1.2 on 2024-07-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alumno_genero_delete_brownie_alumno_id_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
