# Generated by Django 4.1.2 on 2024-07-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_remove_alumno_id_genero_delete_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
