# Generated by Django 4.1.2 on 2024-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagina', '0004_delete_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_genero', models.AutoField(db_column='idContacto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
