# Generated by Django 4.1.2 on 2024-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brownie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='brownies/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='Mensaje',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='id_genero',
        ),
        migrations.AddField(
            model_name='contacto',
            name='idContacto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
